services:
  web:
    ports: !override
      - "127.0.0.1:8001:8000"
    volumes: !override
      - ./staticfiles:/app/staticfiles
    environment:
      FCM_ENABLED: "false"

  scheduler:
    volumes: !override []
    environment:
      FCM_ENABLED: "false"

  nginx:
    ports: !override
      - "80:80"
      - "443:443"
    volumes: !override
      - ./nginx.selectel.conf:/etc/nginx/conf.d/default.conf:ro
      - ./staticfiles:/app/static:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/certbot:/var/www/certbot:ro
