# Generated by Django 5.2.16 on 2026-07-15 11:53

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('category', models.CharField(db_index=True, max_length=50)),
                ('city', models.CharField(db_index=True, max_length=50)),
                ('price', models.PositiveIntegerField(blank=True, null=True)),
                ('contact_phone', models.CharField(blank=True, max_length=20)),
                ('slug', models.SlugField(blank=True, max_length=120, null=True, unique=True)),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('hidden', 'Скрыто'), ('expired', 'Истекло'), ('deleted', 'Удалено')], db_index=True, default='pending', max_length=20)),
                ('images', models.JSONField(blank=True, default=list)),
                ('cover_index', models.PositiveSmallIntegerField(default=0)),
                ('pending_revision', models.JSONField(blank=True, null=True)),
                ('views', models.PositiveIntegerField(default=0)),
                ('contact_clicks', models.PositiveIntegerField(default=0)),
                ('reports_count', models.PositiveIntegerField(default=0)),
                ('rank_score', models.FloatField(db_index=True, default=0.0)),
                ('has_photo', models.BooleanField(default=False)),
                ('paid_until', models.DateTimeField(blank=True, null=True)),
                ('paid_boost', models.FloatField(default=1.0)),
                ('bumped_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(blank=True, null=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('expires_at', models.DateTimeField(db_index=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='posts', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Объявление',
                'verbose_name_plural': 'Объявления',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Promotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=20)),
                ('amount', models.PositiveIntegerField()),
                ('status', models.CharField(db_index=True, default='pending', max_length=20)),
                ('payment_ref', models.CharField(blank=True, max_length=100)),
                ('starts_at', models.DateTimeField(blank=True, null=True)),
                ('ends_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions', to='listings.post')),
            ],
            options={
                'verbose_name': 'Продвижение',
                'verbose_name_plural': 'Продвижения',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reason', models.CharField(max_length=50)),
                ('comment', models.TextField(blank=True)),
                ('reporter_ip', models.GenericIPAddressField(blank=True, null=True)),
                ('status', models.CharField(db_index=True, default='new', max_length=20)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='listings.post')),
                ('reporter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Жалоба',
                'verbose_name_plural': 'Жалобы',
            },
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['city', 'category', 'rank_score'], name='listings_po_city_9d37bd_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['user', 'created_at'], name='listings_po_user_id_b6061e_idx'),
        ),
        migrations.AddIndex(
            model_name='post',
            index=models.Index(fields=['status', 'expires_at'], name='listings_po_status_be5366_idx'),
        ),
    ]
