# Generated by Django 5.2.16 on 2026-07-15 18:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0003_post_ever_published'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('pending', 'На модерации'), ('published', 'Опубликовано'), ('hidden', 'Снято с публикации'), ('expired', 'Истекло'), ('deleted', 'Удалено')], db_index=True, default='pending', max_length=20),
        ),
    ]
