# Generated by Django 6.0.7 on 2026-07-18 11:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('listings', '0006_post_condition'),
        ('locations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='settlement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ads', to='locations.settlement', verbose_name='Населённый пункт'),
        ),
    ]
