# Generated by Django 5.2.16 on 2026-08-04.

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("listings", "0009_poststatusevent_post_status_sold"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="poststatusevent",
            old_name="listings_po_post_id_2d1d71_idx",
            new_name="listings_po_post_id_c41f7b_idx",
        ),
        migrations.AlterField(
            model_name="post",
            name="status",
            field=models.CharField(
                choices=[
                    ("draft", "Черновик"),
                    ("pending", "На модерации"),
                    ("published", "Опубликовано"),
                    ("hidden", "Снято с публикации"),
                    ("sold", "Продано"),
                    ("expired", "Истекло"),
                    ("deleted", "Удалено"),
                ],
                db_index=True,
                default="pending",
                max_length=20,
            ),
        ),
    ]
