# Generated by Django 5.2.16 on 2026-07-15 17:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0002_message_image'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_convers_7bc91b_idx',
            old_name='messaging_m_convers_0a1b2c_idx',
        ),
        migrations.RenameIndex(
            model_name='message',
            new_name='messaging_m_convers_636311_idx',
            old_name='messaging_m_convers_1d2e3f_idx',
        ),
        migrations.AddField(
            model_name='conversation',
            name='buyer_hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='conversation',
            name='seller_hidden_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
