import re
import unicodedata

_RU_MAP = str.maketrans(
    {
        "а": "a",
        "б": "b",
        "в": "v",
        "г": "g",
        "д": "d",
        "е": "e",
        "ё": "yo",
        "ж": "zh",
        "з": "z",
        "и": "i",
        "й": "y",
        "к": "k",
        "л": "l",
        "м": "m",
        "н": "n",
        "о": "o",
        "п": "p",
        "р": "r",
        "с": "s",
        "т": "t",
        "у": "u",
        "ф": "f",
        "х": "h",
        "ц": "ts",
        "ч": "ch",
        "ш": "sh",
        "щ": "sch",
        "ъ": "",
        "ы": "y",
        "ь": "",
        "э": "e",
        "ю": "yu",
        "я": "ya",
        "А": "a",
        "Б": "b",
        "В": "v",
        "Г": "g",
        "Д": "d",
        "Е": "e",
        "Ё": "yo",
        "Ж": "zh",
        "З": "z",
        "И": "i",
        "Й": "y",
        "К": "k",
        "Л": "l",
        "М": "m",
        "Н": "n",
        "О": "o",
        "П": "p",
        "Р": "r",
        "С": "s",
        "Т": "t",
        "У": "u",
        "Ф": "f",
        "Х": "h",
        "Ц": "ts",
        "Ч": "ch",
        "Ш": "sh",
        "Щ": "sch",
        "Ъ": "",
        "Ы": "y",
        "Ь": "",
        "Э": "e",
        "Ю": "yu",
        "Я": "ya",
    }
)


def slugify_ru(value: str) -> str:
    value = (value or "").translate(_RU_MAP).lower()
    value = unicodedata.normalize("NFKD", value)
    value = re.sub(r"[^a-z0-9]+", "-", value).strip("-")
    return value or "location"
