# Generated by Django 6.0.7 on 2026-07-18 11:50

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Region',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(max_length=120, unique=True, verbose_name='Slug')),
                ('code', models.CharField(db_index=True, max_length=16, unique=True, verbose_name='Код GeoNames')),
                ('federal_district', models.CharField(blank=True, default='', max_length=80, verbose_name='Федеральный округ')),
                ('geoname_id', models.PositiveIntegerField(blank=True, null=True, unique=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Регион',
                'verbose_name_plural': 'Регионы',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='locations_r_name_e5c9f5_idx'), models.Index(fields=['slug'], name='locations_r_slug_2acd6c_idx'), models.Index(fields=['code'], name='locations_r_code_975e29_idx')],
            },
        ),
        migrations.CreateModel(
            name='Settlement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=160, verbose_name='Название')),
                ('slug', models.SlugField(max_length=160, verbose_name='Slug')),
                ('type', models.CharField(blank=True, default='населённый пункт', max_length=64, verbose_name='Тип')),
                ('geoname_id', models.PositiveIntegerField(blank=True, db_index=True, null=True, unique=True)),
                ('fias_id', models.CharField(blank=True, db_index=True, default='', max_length=36)),
                ('latitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=6, max_digits=9, null=True)),
                ('population', models.PositiveIntegerField(db_index=True, default=0)),
                ('timezone', models.CharField(blank=True, default='', max_length=64)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('is_popular', models.BooleanField(db_index=True, default=False)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('region', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='settlements', to='locations.region', verbose_name='Регион')),
            ],
            options={
                'verbose_name': 'Населённый пункт',
                'verbose_name_plural': 'Населённые пункты',
                'ordering': ['name'],
                'indexes': [models.Index(fields=['name'], name='locations_s_name_9bc557_idx'), models.Index(fields=['region', 'name'], name='locations_s_region__28cfc1_idx'), models.Index(fields=['region', 'is_active', 'population'], name='locations_s_region__df8d3e_idx'), models.Index(fields=['is_popular', 'population'], name='locations_s_is_popu_2861ae_idx')],
                'constraints': [models.UniqueConstraint(fields=('region', 'slug'), name='unique_settlement_slug_per_region')],
            },
        ),
    ]
